# Generated by Django 3.1.3 on 2021-01-31 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AcessRecord',
            new_name='AccessRecord',
        ),
    ]
